ALTER TABLE credit_card_cycle_payments RENAME TO credit_card_cycle_balances;

DROP INDEX IF EXISTS idx_credit_card_cycle_payments_cycle_id;
DROP INDEX IF EXISTS idx_credit_card_cycle_payments_currency_id;

CREATE INDEX IF NOT EXISTS idx_credit_card_cycle_balances_cycle_id
ON credit_card_cycle_balances(credit_card_cycle_id);

CREATE INDEX IF NOT EXISTS idx_credit_card_cycle_balances_currency_id
ON credit_card_cycle_balances(currency_id);
