/**
 * DOM registry factory.
 *
 * Analogy:
 * - React: similar to collecting stable `ref` handles in one place.
 * - Angular: similar to grouping `@ViewChild` references by feature section.
 * - Vue: similar to a centralized map of template refs consumed by composables.
 */
(function initAppDom(globalScope) {
  /**
   * Builds and returns all DOM references used by feature modules.
   *
   * The returned object acts as a single source of truth for element lookups,
   * avoiding repeated queries and making module contracts explicit.
   *
   * @param {Document} documentRef Browser document reference.
   * @returns {{
   *  transactions: object,
   *  creditCards: object,
   *  creditCardCycles: object,
  *  creditCardCycleBalances: object,
   *  creditCardInstallments: object,
   *  creditCardSubscriptions: object,
   *  expenses: object,
   *  expensePayments: object,
   *  currency: object,
   *  people: object,
   *  bank: object,
   *  bankAccounts: object,
   *  settingsSelectionMessageElement: HTMLElement,
   *  tabButtonElements: NodeListOf<HTMLElement>,
   *  settingsTabButtonElements: NodeListOf<HTMLElement>,
   *  creditCardTabButtonElements: NodeListOf<HTMLElement>,
   *  expenseTabButtonElements: NodeListOf<HTMLElement>,
   *  views: object,
   *  creditCardViews: object,
   *  expenseViews: object,
   *  settingsViews: object
   * }}
   */
  function createAppDom(documentRef) {
    return {
      transactions: {
        openModalButtonElement: documentRef.getElementById("transaction-open-modal-button"),
        modalElement: documentRef.getElementById("transaction-modal"),
        modalTitleElement: documentRef.getElementById("transaction-modal-title"),
        formElement: documentRef.getElementById("transaction-form"),
        idElement: documentRef.getElementById("transaction-id"),
        dateElement: documentRef.getElementById("transaction-date"),
        typeElement: documentRef.getElementById("transaction-type"),
        amountElement: documentRef.getElementById("transaction-amount"),
        notesElement: documentRef.getElementById("transaction-notes"),
        personIdElement: documentRef.getElementById("transaction-person-id"),
        bankAccountIdElement: documentRef.getElementById("transaction-bank-account-id"),
        categoryIdElement: documentRef.getElementById("transaction-category-id-input"),
        submitButtonElement: documentRef.getElementById("transaction-submit-button"),
        cancelButtonElement: documentRef.getElementById("transaction-cancel-button"),
        messageElement: documentRef.getElementById("transaction-form-message"),
        bodyElement: documentRef.getElementById("transactions-body"),
      },
      creditCards: {
        openModalButtonElement: documentRef.getElementById("credit-card-open-modal-button"),
        modalElement: documentRef.getElementById("credit-card-modal"),
        modalTitleElement: documentRef.getElementById("credit-card-modal-title"),
        formElement: documentRef.getElementById("credit-card-form"),
        idElement: documentRef.getElementById("credit-card-id"),
        bankIdElement: documentRef.getElementById("credit-card-bank-id"),
        personIdElement: documentRef.getElementById("credit-card-person-id"),
        numberElement: documentRef.getElementById("credit-card-number"),
        nameElement: documentRef.getElementById("credit-card-name"),
        submitButtonElement: documentRef.getElementById("credit-card-submit-button"),
        cancelButtonElement: documentRef.getElementById("credit-card-cancel-button"),
        messageElement: documentRef.getElementById("credit-card-form-message"),
        bodyElement: documentRef.getElementById("credit-cards-body"),
      },
      creditCardCycles: {
        openModalButtonElement: documentRef.getElementById("credit-card-cycle-open-modal-button"),
        modalElement: documentRef.getElementById("credit-card-cycle-modal"),
        modalTitleElement: documentRef.getElementById("credit-card-cycle-modal-title"),
        formElement: documentRef.getElementById("credit-card-cycle-form"),
        idElement: documentRef.getElementById("credit-card-cycle-id"),
        creditCardIdElement: documentRef.getElementById("credit-card-cycle-credit-card-id"),
        closingDateElement: documentRef.getElementById("credit-card-cycle-closing-date"),
        dueDateElement: documentRef.getElementById("credit-card-cycle-due-date"),
        submitButtonElement: documentRef.getElementById("credit-card-cycle-submit-button"),
        cancelButtonElement: documentRef.getElementById("credit-card-cycle-cancel-button"),
        messageElement: documentRef.getElementById("credit-card-cycle-form-message"),
        bodyElement: documentRef.getElementById("credit-card-cycles-body"),
      },
      creditCardCycleBalances: {
        openModalButtonElement: documentRef.getElementById("credit-card-cycle-balance-open-modal-button"),
        modalElement: documentRef.getElementById("credit-card-cycle-balance-modal"),
        modalTitleElement: documentRef.getElementById("credit-card-cycle-balance-modal-title"),
        formElement: documentRef.getElementById("credit-card-cycle-balance-form"),
        idElement: documentRef.getElementById("credit-card-cycle-balance-id"),
        cycleIdElement: documentRef.getElementById("credit-card-cycle-balance-cycle-id"),
        currencyIdElement: documentRef.getElementById("credit-card-cycle-balance-currency-id"),
        balanceElement: documentRef.getElementById("credit-card-cycle-balance-balance"),
        paidElement: documentRef.getElementById("credit-card-cycle-balance-paid"),
        submitButtonElement: documentRef.getElementById("credit-card-cycle-balance-submit-button"),
        cancelButtonElement: documentRef.getElementById("credit-card-cycle-balance-cancel-button"),
        messageElement: documentRef.getElementById("credit-card-cycle-balance-form-message"),
        bodyElement: documentRef.getElementById("credit-card-cycle-balances-body"),
      },
      creditCardInstallments: {
        openModalButtonElement: documentRef.getElementById("credit-card-installment-open-modal-button"),
        modalElement: documentRef.getElementById("credit-card-installment-modal"),
        modalTitleElement: documentRef.getElementById("credit-card-installment-modal-title"),
        formElement: documentRef.getElementById("credit-card-installment-form"),
        idElement: documentRef.getElementById("credit-card-installment-id"),
        creditCardIdElement: documentRef.getElementById("credit-card-installment-credit-card-id"),
        currencyIdElement: documentRef.getElementById("credit-card-installment-currency-id"),
        conceptElement: documentRef.getElementById("credit-card-installment-concept"),
        amountElement: documentRef.getElementById("credit-card-installment-amount"),
        startDateElement: documentRef.getElementById("credit-card-installment-start-date"),
        countElement: documentRef.getElementById("credit-card-installment-count"),
        submitButtonElement: documentRef.getElementById("credit-card-installment-submit-button"),
        cancelButtonElement: documentRef.getElementById("credit-card-installment-cancel-button"),
        messageElement: documentRef.getElementById("credit-card-installment-form-message"),
        bodyElement: documentRef.getElementById("credit-card-installments-body"),
      },
      creditCardSubscriptions: {
        openModalButtonElement: documentRef.getElementById("credit-card-subscription-open-modal-button"),
        modalElement: documentRef.getElementById("credit-card-subscription-modal"),
        modalTitleElement: documentRef.getElementById("credit-card-subscription-modal-title"),
        formElement: documentRef.getElementById("credit-card-subscription-form"),
        idElement: documentRef.getElementById("credit-card-subscription-id"),
        creditCardIdElement: documentRef.getElementById("credit-card-subscription-credit-card-id"),
        currencyIdElement: documentRef.getElementById("credit-card-subscription-currency-id"),
        conceptElement: documentRef.getElementById("credit-card-subscription-concept"),
        amountElement: documentRef.getElementById("credit-card-subscription-amount"),
        submitButtonElement: documentRef.getElementById("credit-card-subscription-submit-button"),
        cancelButtonElement: documentRef.getElementById("credit-card-subscription-cancel-button"),
        messageElement: documentRef.getElementById("credit-card-subscription-form-message"),
        bodyElement: documentRef.getElementById("credit-card-subscriptions-body"),
      },
      expenses: {
        openModalButtonElement: documentRef.getElementById("expense-open-modal-button"),
        modalElement: documentRef.getElementById("expense-modal"),
        modalTitleElement: documentRef.getElementById("expense-modal-title"),
        formElement: documentRef.getElementById("expense-form"),
        idElement: documentRef.getElementById("expense-id"),
        nameElement: documentRef.getElementById("expense-name"),
        frequencyElement: documentRef.getElementById("expense-frequency"),
        submitButtonElement: documentRef.getElementById("expense-submit-button"),
        cancelButtonElement: documentRef.getElementById("expense-cancel-button"),
        messageElement: documentRef.getElementById("expense-form-message"),
        bodyElement: documentRef.getElementById("expenses-body"),
      },
      expensePayments: {
        openModalButtonElement: documentRef.getElementById("expense-payment-open-modal-button"),
        modalElement: documentRef.getElementById("expense-payment-modal"),
        modalTitleElement: documentRef.getElementById("expense-payment-modal-title"),
        formElement: documentRef.getElementById("expense-payment-form"),
        idElement: documentRef.getElementById("expense-payment-id"),
        expenseIdElement: documentRef.getElementById("expense-payment-expense-id"),
        amountElement: documentRef.getElementById("expense-payment-amount"),
        currencyIdElement: documentRef.getElementById("expense-payment-currency-id"),
        dateElement: documentRef.getElementById("expense-payment-date"),
        submitButtonElement: documentRef.getElementById("expense-payment-submit-button"),
        cancelButtonElement: documentRef.getElementById("expense-payment-cancel-button"),
        messageElement: documentRef.getElementById("expense-payment-form-message"),
        bodyElement: documentRef.getElementById("expense-payments-body"),
      },
      currency: {
        openModalButtonElement: documentRef.getElementById("currency-open-modal-button"),
        modalElement: documentRef.getElementById("currency-modal"),
        modalTitleElement: documentRef.getElementById("currency-modal-title"),
        formElement: documentRef.getElementById("currency-form"),
        idElement: documentRef.getElementById("currency-id"),
        nameElement: documentRef.getElementById("currency-name"),
        codeElement: documentRef.getElementById("currency-code"),
        submitButtonElement: documentRef.getElementById("currency-submit-button"),
        cancelButtonElement: documentRef.getElementById("currency-cancel-button"),
        messageElement: documentRef.getElementById("currency-form-message"),
        bodyElement: documentRef.getElementById("currencies-body"),
      },
      people: {
        openModalButtonElement: documentRef.getElementById("person-open-modal-button"),
        modalElement: documentRef.getElementById("person-modal"),
        modalTitleElement: documentRef.getElementById("person-modal-title"),
        formElement: documentRef.getElementById("person-form"),
        idElement: documentRef.getElementById("person-id"),
        nameElement: documentRef.getElementById("person-name"),
        submitButtonElement: documentRef.getElementById("person-submit-button"),
        cancelButtonElement: documentRef.getElementById("person-cancel-button"),
        messageElement: documentRef.getElementById("person-form-message"),
        bodyElement: documentRef.getElementById("people-body"),
      },
      transactionCategories: {
        openModalButtonElement: documentRef.getElementById("transaction-category-open-modal-button"),
        modalElement: documentRef.getElementById("transaction-category-modal"),
        modalTitleElement: documentRef.getElementById("transaction-category-modal-title"),
        formElement: documentRef.getElementById("transaction-category-form"),
        idElement: documentRef.getElementById("transaction-category-id"),
        nameElement: documentRef.getElementById("transaction-category-name"),
        parentIdElement: documentRef.getElementById("transaction-category-parent-id"),
        submitButtonElement: documentRef.getElementById("transaction-category-submit-button"),
        cancelButtonElement: documentRef.getElementById("transaction-category-cancel-button"),
        messageElement: documentRef.getElementById("transaction-category-form-message"),
        bodyElement: documentRef.getElementById("transaction-categories-body"),
      },
      bank: {
        openModalButtonElement: documentRef.getElementById("bank-open-modal-button"),
        modalElement: documentRef.getElementById("bank-modal"),
        modalTitleElement: documentRef.getElementById("bank-modal-title"),
        formElement: documentRef.getElementById("bank-form"),
        idElement: documentRef.getElementById("bank-id"),
        nameElement: documentRef.getElementById("bank-name"),
        countryElement: documentRef.getElementById("bank-country"),
        submitButtonElement: documentRef.getElementById("bank-submit-button"),
        cancelButtonElement: documentRef.getElementById("bank-cancel-button"),
        messageElement: documentRef.getElementById("bank-form-message"),
        bodyElement: documentRef.getElementById("banks-body"),
      },
      bankAccounts: {
        openModalButtonElement: documentRef.getElementById("bank-account-open-modal-button"),
        modalElement: documentRef.getElementById("bank-account-modal"),
        modalTitleElement: documentRef.getElementById("bank-account-modal-title"),
        formElement: documentRef.getElementById("bank-account-form"),
        idElement: documentRef.getElementById("bank-account-id"),
        bankIdElement: documentRef.getElementById("bank-account-bank-id"),
        currencyIdElement: documentRef.getElementById("bank-account-currency-id"),
        accountNumberElement: documentRef.getElementById("bank-account-number"),
        balanceElement: documentRef.getElementById("bank-account-balance"),
        submitButtonElement: documentRef.getElementById("bank-account-submit-button"),
        cancelButtonElement: documentRef.getElementById("bank-account-cancel-button"),
        messageElement: documentRef.getElementById("bank-account-form-message"),
        bodyElement: documentRef.getElementById("bank-accounts-body"),
      },
      settingsSelectionMessageElement: documentRef.getElementById("settings-selection-message"),
      tabButtonElements: documentRef.querySelectorAll("[data-route-tab]"),
      settingsTabButtonElements: documentRef.querySelectorAll("[data-settings-tab]"),
      creditCardTabButtonElements: documentRef.querySelectorAll("[data-credit-card-tab]"),
      expenseTabButtonElements: documentRef.querySelectorAll("[data-expense-tab]"),
      views: {
        home: documentRef.getElementById("view-home"),
        transactions: documentRef.getElementById("view-transactions"),
        creditCards: documentRef.getElementById("view-credit-cards"),
        expenses: documentRef.getElementById("view-expenses"),
        settings: documentRef.getElementById("view-settings"),
      },
      creditCardViews: {
        cards: documentRef.getElementById("view-credit-cards-cards"),
        cycles: documentRef.getElementById("view-credit-card-cycles"),
        balances: documentRef.getElementById("view-credit-card-balances"),
        installments: documentRef.getElementById("view-credit-card-installments"),
        subscriptions: documentRef.getElementById("view-credit-card-subscriptions"),
      },
      expenseViews: {
        expenses: documentRef.getElementById("view-expenses-expenses"),
        payments: documentRef.getElementById("view-expenses-payments"),
      },
      settingsViews: {
        currency: documentRef.getElementById("view-currency"),
        people: documentRef.getElementById("view-people"),
        transactionCategories: documentRef.getElementById("view-transaction-categories"),
        banks: documentRef.getElementById("view-banks"),
        bankAccounts: documentRef.getElementById("view-bank-accounts"),
      },
    };
  }

  if (typeof module !== "undefined" && module.exports) {
    module.exports = { createAppDom };
    return;
  }

  globalScope.createAppDom = createAppDom;
})(typeof globalThis !== "undefined" ? globalThis : window);
